database_service_name: postgresql-rhdh-ls
config:
  port: 5432
  postgresql_database: rhdh-ls
  postgresql_user: lightspeed
  postgresql_password: l1ghtsp33d
image:
  tag: "15-el9"
memory_limit: 1Gi
volume_capacity: 1Gi
