apiVersion: rhdh.redhat.com/v1alpha4
kind: Backstage
metadata:
  name: developer-hub
spec:
  deployment:
    patch:
      spec:
        replicas: 4
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
        #strategy:
        #  #rollingUpdate: null
        #  rollingUpdate:
        #    $patch: delete
        #  type: Recreate                            
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: app-config-rhdh
    extraFiles:
      mountPath: /opt/app-root/src/rbac
      configMaps:
        - name: rbac-policy
    extraEnvs:
      envs:
        # Disabling TLS verification
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
          containers:
            - '*'
      configMaps:
        - name: rhdh-techdocs-bucket-claim
      secrets:
        - name: gitlab-secrets
        - name: rhdh-secrets
        - name: rhdh-techdocs-bucket-claim
    route:
      enabled: true
  database:
    enableLocalDb: true
  monitoring:
    enabled: true
  rawRuntimeConfig:
    localDbConfig: postgresql-config
